# Multi-package project Makefile script.
.POSIX:
help:

#MAKE = make # (GNU make variants: make (Linux) gmake (FreeBSD)

parent = {{parent}}{{^parent}}introclj{{/parent}}
SUBDIRS = common app

.PHONY: all clean compile help install test
help: $(SUBDIRS)
	-for dirX in $^ ; do (cd $$dirX ; lein help) ; done
	@echo "##### Top-level multiproject: $(parent) #####"
	@echo "Usage: $(MAKE) [SUBDIRS="$(SUBDIRS)"] [target]"
all compile: $(SUBDIRS)
	-for dirX in $^ ; do (cd $$dirX ; lein compile :all) ; done
test: $(SUBDIRS)
	-for dirX in $^ ; do (cd $$dirX ; lein test) ; done
install: $(SUBDIRS)
	-for dirX in $^ ; do (cd $$dirX ; lein install) ; done
clean: $(SUBDIRS)
	-for dirX in $^ ; do (cd $$dirX ; lein clean) ; done
	-rm -fr core* *~ .*~ target/* *.log */*.log

#----------------------------------------
FMTS ?= tar.gz
distdir = $(parent)-0.1.0

.PHONY: dist doc lint cover run
dist: $(SUBDIRS)
	-@mkdir -p target/$(distdir) ; cp -f exclude.lst target/
#	#-zip -9 -q --exclude @exclude.lst -r - . | unzip -od target/$(distdir) -
	-tar --format=posix --dereference --exclude-from=exclude.lst -cf - . | tar -xpf - -C target/$(distdir)
	
	-@for fmt in `echo $(FMTS) | tr ',' ' '` ; do \
		case $$fmt in \
			zip) echo "### target/$(distdir).zip ###" ; \
				rm -f target/$(distdir).zip ; \
				(cd target ; zip -9 -q -r $(distdir).zip $(distdir)) ;; \
			*) tarext=`echo $$fmt | grep -e '^tar$$' -e '^tar.xz$$' -e '^tar.bz2$$' || echo tar.gz` ; \
				echo "### target/$(distdir).$$tarext ###" ; \
				rm -f target/$(distdir).$$tarext ; \
				(cd target ; tar --posix -L -caf $(distdir).$$tarext $(distdir)) ;; \
		esac \
	done
	-@rm -r target/$(distdir)
	-for dirX in $^ ; do $(MAKE) -C $$dirX $@ ; done
doc: $(SUBDIRS)
	-for dirX in $^ ; do (cd $$dirX ; lein codox) ; done
lint: $(SUBDIRS)
	-for dirX in $^ ; do (cd $$dirX ; lein eastwood) ; done
cover: $(SUBDIRS)
	-for dirX in $^ ; do (cd $$dirX ; lein cloverage) ; done
run: app
	-(cd app ; lein run)
