# Multi-package project Makefile script.
.POSIX:
help:

#MAKE = make # (GNU make variants: make (Linux) gmake (FreeBSD)

parent = {{parent}}{{^parent}}intro_jvm{{/parent}}
version = {{version}}{{^version}}0.1.0{{/version}}
SUBDIRS = common app

.PHONY: all clean compile help install test
help: $(SUBDIRS)
	-for dirX in $^ ; do (cd $$dirX ; ./leinw help) ; done
	@echo "##### Top-level multiproject: $(parent) #####"
	@echo "Usage: $(MAKE) [SUBDIRS="$(SUBDIRS)"] [target]"
all compile: $(SUBDIRS)
	-for dirX in $^ ; do (cd $$dirX ; ./leinw compile :all) ; done
test: $(SUBDIRS)
	-for dirX in $^ ; do (cd $$dirX ; ./leinw test) ; done
install: $(SUBDIRS)
	-for dirX in $^ ; do (cd $$dirX ; ./leinw install) ; done
clean: $(SUBDIRS)
	-for dirX in $^ ; do (cd $$dirX ; ./leinw clean) ; done
	-rm -fr core* *~ .*~ target/* *.log */*.log

#----------------------------------------
FMTS ?= tar.gz,zip
distdir = $(parent)-$(version)

target/$(distdir) :
	-@mkdir -p target/$(distdir) ; cp -f exclude.lst target/
#	#-zip -9 -q --exclude @exclude.lst -r - . | unzip -od target/$(distdir) -
	-tar --format=posix --dereference --exclude-from=exclude.lst -cf - . | tar -xpf - -C target/$(distdir)

.PHONY: dist doc lint cover run
dist | target/$(distdir): $(SUBDIRS)
	-@for fmt in `echo $(FMTS) | tr ',' ' '` ; do \
		case $$fmt in \
			7z) echo "### target/$(distdir).7z ###" ; \
				rm -f target/$(distdir).7z ; \
				(cd target ; 7za a -t7z -mx=9 $(distdir).7z $(distdir)) ;; \
			zip) echo "### target/$(distdir).zip ###" ; \
				rm -f target/$(distdir).zip ; \
				(cd target ; zip -9 -q -r $(distdir).zip $(distdir)) ;; \
			*) tarext=`echo $$fmt | grep -e '^tar$$' -e '^tar.xz$$' -e '^tar.zst$$' -e '^tar.bz2$$' || echo tar.gz` ; \
				echo "### target/$(distdir).$$tarext ###" ; \
				rm -f target/$(distdir).$$tarext ; \
				(cd target ; tar --posix -h -caf $(distdir).$$tarext $(distdir)) ;; \
		esac \
	done
	-@rm -r target/$(distdir)
	-for dirX in $^ ; do $(MAKE) -C $$dirX $@ ; done
doc: $(SUBDIRS)
	-for dirX in $^ ; do (cd $$dirX ; ./leinw codox) ; done
lint: $(SUBDIRS)
	-for dirX in $^ ; do (cd $$dirX ; ./leinw eastwood) ; done
cover: $(SUBDIRS)
	-for dirX in $^ ; do (cd $$dirX ; ./leinw cloverage) ; done
run: app
	-(cd app ; ./leinw run)
